version: '3.8'

services:
  monitor:
    image: system-monitor
    container_name: system-monitor
    networks:
      - portainer_default
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
      labels:
        - traefik.enable=true
        - traefik.http.routers.monitor.rule=Host(`sub-domonio.dominio.com`)
        - traefik.http.routers.monitor.entrypoints=websecure
        - traefik.http.routers.monitor.tls=true
        - traefik.http.routers.monitor.tls.certresolver=letsencryptresolver
        - traefik.http.services.monitor.loadbalancer.server.port=3000
      
    restart: unless-stopped
    privileged: true
    volumes:
      - /:/host
    environment:
      - SI_DISABLE_CHECK=true
      - API_KEY=sua_api_key

networks:
  portainer_default:
    external: true
    name: portainer_default
